# fly.toml app configuration file generated for baka on 2025-09-30T20:12:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'baka'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
 
